version : '2'

services:
  web_1:
    build: ./nginx
    ports:
      - 8000:80
    volumes:
      - ./app/web_1:/myapp/web_1
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/sites-enabled/web_1.local.conf:/etc/nginx/sites-enabled/web_1.local.conf
      - ./logs:/logs
    links:
      - php
    hostname: "web_1.local"
  web_2:
    build: ./nginx
    ports:
      - 8001:80
    volumes:
      - ./app/web_2:/myapp/web_2
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/sites-enabled/web_2.local.conf:/etc/nginx/sites-enabled/web_2.local.conf
      - ./logs:/logs
    links:
      - php
    hostname: "web_1.local"
  
  terra:
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - ./app/terra:/myapp/terra
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/sites-enabled/terra.sepulsa.local.conf:/etc/nginx/sites-enabled/terra.sepulsa.local.conf
      - ./logs:/logs
    links:
      - php
    hostname: "terra.sepulsa.local"
  meowth:
    build: ./nginx
    ports:
      - 8081:80
    volumes:
      - ./app/meowth:/myapp/meowth
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/sites-enabled/meowth.sepulsa.local.conf:/etc/nginx/sites-enabled/meowth.sepulsa.local.conf
      - ./logs:/logs
    links:
      - php
    hostname: "meowth.sepulsa.local"
  php:
    build: ./php
    volumes:
      - ./app:/myapp

networks: 
  default:
    external:
      name: my-shared-network