version : '2'

services:
  terra:
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - ./app/terra:/myapp/terra
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/sites-enabled/terra.sepulsa.local.conf:/etc/nginx/sites-enabled/terra.sepulsa.local.conf
      - ./logs:/logs
    links:
      - php
    hostname: "terra.sepulsa.local"
  meowth:
    build: ./nginx
    ports:
      - 8081:80
    volumes:
      - ./app/meowth:/myapp/meowth
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/sites-enabled/meowth.sepulsa.local.conf:/etc/nginx/sites-enabled/meowth.sepulsa.local.conf
      - ./logs:/logs
    links:
      - php
    hostname: "meowth.sepulsa.local"
  php:
    build: ./php
    volumes:
      - ./app:/myapp

networks: 
  default:
    external:
      name: my-shared-network