version : '2'

services:
  web:
      build: ./nginx
      ports:
        - 80:80
      volumes:
        - ./app:/myapp
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./nginx/sites-enabled:/etc/nginx/sites-enabled
        - ./logs:/logs
      links:
        - php
  php:
    build: ./php
    volumes:
      - ./app:/myapp
    extra_hosts:
      - "meowth.sepulsa.local:127.0.0.1"
      - "elissian.sepulsa.local:127.0.0.2"

networks: 
  default:
    external:
      name: my-shared-network